"""Add tenant_id fields

Revision ID: 6aaa256c041f
Revises: aba288c52897
Create Date: 2026-07-12 12:33:34.534217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aaa256c041f'
down_revision: Union[str, Sequence[str], None] = 'aba288c52897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkin_runs', sa.Column('tenant_id', sa.String(length=50), server_default='default_tenant', nullable=False))
    op.add_column('family_profiles', sa.Column('tenant_id', sa.String(length=50), server_default='default_tenant', nullable=False))
    op.add_column('learner_profiles', sa.Column('tenant_id', sa.String(length=50), server_default='default_tenant', nullable=False))
    op.add_column('sessions', sa.Column('tenant_id', sa.String(length=50), server_default='default_tenant', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'tenant_id')
    op.drop_column('learner_profiles', 'tenant_id')
    op.drop_column('family_profiles', 'tenant_id')
    op.drop_column('checkin_runs', 'tenant_id')
    # ### end Alembic commands ###
