"""add_v9_quality_and_optimizer_tables

Revision ID: dfe151ba9884
Revises: 9a5857cc6fbd
Create Date: 2026-07-12 13:42:11.315371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe151ba9884'
down_revision: Union[str, Sequence[str], None] = '9a5857cc6fbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
