import os
import json
import logging
from typing import List, Dict, Any, TypeVar, Type, Optional, Generic
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

logger = logging.getLogger(__name__)

class BaseFileRepository:
    """Base repository class handling reads/writes from/to JSONL database files on disk."""

    def __init__(self, filepath: str):
        self.filepath = filepath
        # Ensure directories exist
        dir_path = os.path.dirname(os.path.abspath(self.filepath))
        os.makedirs(dir_path, exist_ok=True)
        # Create target database file if missing
        if not os.path.exists(self.filepath):
            with open(self.filepath, "w", encoding="utf-8") as f:
                pass

    def _read_lines(self) -> List[Dict[str, Any]]:
        """Reads and parses each line of the JSONL store."""
        records = []
        if not os.path.exists(self.filepath):
            return records
            
        try:
            with open(self.filepath, "r", encoding="utf-8") as f:
                for line in f:
                    stripped = line.strip()
                    if stripped:
                        try:
                            records.append(json.loads(stripped))
                        except json.JSONDecodeError as decode_err:
                            logger.error(f"Failed parsing JSON line in {self.filepath}: {stripped}. Err: {decode_err}")
        except IOError as io_err:
            logger.error(f"Failed opening database file {self.filepath}: {io_err}")
            
        return records

    def _append_line(self, record: Dict[str, Any]) -> None:
        """Appends a single JSON dictionary record to the database file."""
        try:
            with open(self.filepath, "a", encoding="utf-8") as f:
                f.write(json.dumps(record) + "\n")
        except IOError as io_err:
            logger.error(f"Failed appending record to {self.filepath}: {io_err}")
            raise RuntimeError(f"Database write failure: {str(io_err)}")
            
    def _overwrite_all(self, records: List[Dict[str, Any]]) -> None:
        """Re-writes the entire file with new record contents."""
        try:
            # Atomic rewrite via temporary file
            temp_path = self.filepath + ".tmp"
            with open(temp_path, "w", encoding="utf-8") as f:
                for record in records:
                    f.write(json.dumps(record) + "\n")
            if os.path.exists(self.filepath):
                os.remove(self.filepath)
            os.rename(temp_path, self.filepath)
        except IOError as io_err:
            logger.error(f"Failed overwriting database file {self.filepath}: {io_err}")
            raise RuntimeError(f"Database replace failure: {str(io_err)}")

# Type Variable representing database models
T = TypeVar("T")

class BaseDBRepository(Generic[T]):
    """Base database repository utilizing SQLAlchemy async session sessions for storage transactions."""

    def __init__(self, db: AsyncSession, model_cls: Type[T]):
        self.db = db
        self.model_cls = model_cls

    async def get_by_id(self, entity_id: str) -> Optional[T]:
        """Fetches a model entity record matching the identifier key."""
        stmt = select(self.model_cls).filter(self.model_cls.id == entity_id)
        result = await self.db.execute(stmt)
        return result.scalars().first()

    async def get_by_id_and_tenant(self, entity_id: str, tenant_id: str = "default_tenant") -> Optional[T]:
        """Fetches a model entity record matching the identifier key and tenant scope."""
        if hasattr(self.model_cls, "tenant_id"):
            stmt = select(self.model_cls).filter(
                self.model_cls.id == entity_id,
                self.model_cls.tenant_id == tenant_id
            )
        else:
            stmt = select(self.model_cls).filter(self.model_cls.id == entity_id)
        result = await self.db.execute(stmt)
        return result.scalars().first()

    async def create(self, entity: T) -> T:
        """Adds a new model entity record to the database session mapping."""
        self.db.add(entity)
        await self.db.flush()  # Populates autogenerated fields without committing
        return entity

    async def save(self, entity: T) -> T:
        """Saves or updates an entity record."""
        self.db.add(entity)
        await self.db.flush()
        return entity

    async def delete(self, entity: T) -> None:
        """Removes a target entity record from session mappings."""
        await self.db.delete(entity)
        await self.db.flush()

    async def get_all_by_tenant(self, tenant_id: str = "default_tenant") -> List[T]:
        """Fetches all model entity records matching the tenant scope."""
        if hasattr(self.model_cls, "tenant_id"):
            stmt = select(self.model_cls).filter(self.model_cls.tenant_id == tenant_id)
        else:
            stmt = select(self.model_cls)
        result = await self.db.execute(stmt)
        return list(result.scalars().all())
